### ISSUE TITLE
hide child divider

### ISSUE THREAD

**Issue by chitrey** [ngocchung/ThreeLevelExpListView#2]
Hi i am able to hide the divider by using by setting divider:"@null" but i cannot seem to hide the divider of the childDivider (i.e Level 1.1.1 and Third Level 01). Could you please tell me how to achieve this? I've tried setting childDivider to null as well as set its color to transparent but nothing seems to work

**Comment by ngocchung** [comment]
@chitrey sorry for late reply, Have you tried `secondLevelExpListView.setChildDivider(ContextCompat.getDrawable(mContext, R.color.transparent));` right above `return secondLevelExpListView;` inside `getChildView` of `ParentLevelAdapter.java` file? Pls see the screenshot
![device-2017-03-07-152957](https://cloud.githubusercontent.com/assets/13657098/23648085/ad84127a-034b-11e7-9715-52340eb2f08b.png)
